replicaCount: 2

resources:
  requests:
    cpu: 60m
    memory: 60M
livenessProbe:
  httpGet:
    path: /api/v1/healthz
    port: http
readinessProbe:
  httpGet:
    path: /api/v1/healthz
    port: http