replicaCount: 2
image:
  repository: niketjoshi/${{values.app_name}}
  pullPolicy: IfNotPresent
  tag: ${{values.app_name}}-${{values.app_env}}-latest

resources:
  requests:
    cpu: 60m
    memory: 60M
livenessProbe:
  httpGet:
    path: /api/v1/healthz
    port: http
readinessProbe:
  httpGet:
    path: /api/v1/healthz
    port: http